### ISSUE TITLE
include overall-scan

### ISSUE THREAD

**Issue by snmnzl** [qurator-spk/neat#45]
I know we have been discussing this before, but annotating on the new documents has shown that OCR often leaves out several sections or lines. This makes it necessary to have an overview of the full page. We can display the page on ZEFYS in most cases, but it costs extra time and is not possible with the pages that are not online yet. Therefore, would it be possible to link the full scan (e.g. on the upper display of the filename in neath)?

**Comment by cneud** [comment]
OK, we can look into this after fixing the recently reported bugs.

Meanwhile, when you click on the snippet, it will open a larger snippet in a new browser tab. In that tab, you can alter the URL by replacing the part with the coordinates by `full` to display the full image instead, e.g.   
https://content.staatsbibliothek-berlin.de/zefys/SNP27646518-18800101-0-3-0-0/0,175,662,469/full/0/default.jpg   
-->   
https://content.staatsbibliothek-berlin.de/zefys/SNP27646518-18800101-0-3-0-0/full/full/0/default.jpg

**Comment by labusch** [comment]
Now, there is a little full page link below the image snippet.

**Comment by snmnzl** [comment]
@labusch Great, this is a very helpful shortcut! Thx
