### ISSUE TITLE
[ocr] keyboard layouts

### ISSUE THREAD

**Issue by cneud** [qurator-spk/neat#50]
[Here](https://gist.github.com/cneud/1b9b27fe60ad0366f787f9bef72131da) is one based on the Unicode subset from the [OCR-D Guidelines](https://ocr-d.de/en/gt-guidelines/trans/ocr_d_koordinationsgremium_codierung.html).

**Comment by labusch** [comment]
OCR-D keyboard layout has been applied.

**Comment by labusch** [comment]
see above
